repos:
  - repo: local
    hooks:
      - id: golangci-lint-swag-fmt
        name: run golangci-and-swag-lint per directory
        entry: scripts/run-golangci-and-swag-lint.sh
        language: system
        types: [go]
        stages: [pre-commit]
        require_serial: true
        verbose: true