services:
  postgres:
    image: postgres:16
    container_name: marketplace_postgres
    env_file: .env
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  goose:
    container_name: marketplace_goose
    build:
      context: ./migrations
      dockerfile: Dockerfile
    env_file: .env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      MIGRATION_VERSION: ${MIGRATION_VERSION:-latest}
    volumes:
      - ./migrations/sql:/migrations/sql
    depends_on:
      postgres:
        condition: service_healthy

  mongodb:
    image: mongo:5
    container_name: marketplace_mongodb
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 5s
      timeout: 10s
      retries: 5

  marketplace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace_app
    env_file: .env
    ports:
      - "${PORT}:8081"
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy

volumes:
  postgres_data:
  mongodb_data:
